import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import AccordionItem from "../components/accordian/accordianItem";
import Dropdown from "../components/dropdown/dropdown";
import Stepper from "../components/stepper-modals/stepper";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const [selectedItem, setSelectedItem] = useState<any>({});
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Endpoints</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Simply<a href="https://nextjs.org">Start!</a>
        </h1>

        <p className={styles.description}></p>

        <div className={styles.grid}>
          <Link href={"/auth/signup"}>
            <a className={styles.card}>
              <h2>Signup Page</h2>
              <p>
                Endpoint :<code>/auth/signup</code>
              </p>
            </a>
          </Link>
          <Link href={"/auth/login"}>
            <a className={styles.card}>
              <h2>Login Page</h2>
              <p>
                Endpoint : <code>/auth/login</code>
              </p>
            </a>
          </Link>
          <Link href={"/auth/login/forgot-password"}>
            <a className={styles.card}>
              <h2>Forgot Password </h2>
              <p>
                Endpoint : <code>/auth/login/forgot-password</code>
              </p>
            </a>
          </Link>

          <p>Selected Value: {selectedItem?.name}</p>

          {/* <Dropdown
            items={[
              { name: "Signup", id: 1 },
              { name: "Login", id: 2 },
            ]}
            getSelectedItem={(item) => {
              setSelectedItem(item);
            }}
          /> */}
        </div>
        <div style={{ width: "100%", padding: "20px 10px" }}>
          <Stepper />
        </div>
        <div>
          {/* <AccordionItem faq={{ question: "hi", answer: "hello" }} getValue={ null} /> */}
        </div>
      </main>
    </div>
  );
};

export default Home;
